---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neon.oltp.molnett.org
  resources:
  - branches
  - clusters
  - databases
  - endpoints
  - operations
  - pageservers
  - projects
  - roles
  - safekeepers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neon.oltp.molnett.org
  resources:
  - branches/finalizers
  - clusters/finalizers
  - databases/finalizers
  - endpoints/finalizers
  - pageservers/finalizers
  - projects/finalizers
  - roles/finalizers
  - safekeepers/finalizers
  verbs:
  - update
- apiGroups:
  - neon.oltp.molnett.org
  resources:
  - branches/status
  - clusters/status
  - databases/status
  - endpoints/status
  - operations/status
  - pageservers/status
  - projects/status
  - roles/status
  - safekeepers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
