---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: storage-controller-pg-cluster
  namespace: neon
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: storage_controller
      owner: storage_controller
      secret:
        name: storage-controller-user

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-controller-user
  namespace: neon
type: kubernetes.io/basic-auth
data:
  username: c3RvcmFnZV9jb250cm9sbGVy
  password: c3RvcmFnZV9jb250cm9sbGVy

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-controller-pg-cluster-app
  namespace: neon
type: Opaque
stringData:
  uri: "postgres://storage_controller:storage_controller@storage-controller-pg-cluster-rw.neon.svc:5432/storage_controller"