kind: Cluster
apiVersion: neon.oltp.molnett.org/v1alpha1
metadata:
  name: my-cluster
  namespace: neon
spec:
  numSafekeepers: 3
  numPageservers: 2
  defaultPGVersion: 16
  neonImage: "192.168.232.128:5000/neondatabase/neon:8463"
  bucketCredentialsSecret:
    name: bucket-creds
  storageControllerDatabaseSecret:
    name: storage-controller-pg-cluster
    key: uri
  defaultSafekeeperStorage:
    size: 5Gi
