---
kind: Pageserver
apiVersion: neon.oltp.molnett.org/v1alpha1
metadata:
  name: my-cluster-pageserver-1
  namespace: neon
spec:
  id: 1
  cluster: my-cluster
  bucketCredentialsSecret:
    name: bucket-creds
  storageConfig:
    size: 20Gi
---
kind: Pageserver
apiVersion: neon.oltp.molnett.org/v1alpha1
metadata:
  name: my-cluster-pageserver-2
  namespace: neon
spec:
  id: 2
  cluster: my-cluster
  bucketCredentialsSecret:
    name: bucket-creds
  storageConfig:
    size: 10Gi
