---
kind: Safekeeper
apiVersion: neon.oltp.molnett.org/v1alpha1
metadata:
  name: my-cluster-safekeeper-1
  namespace: neon
spec:
  id: 1
  cluster: my-cluster
  storageConfig:
    size: 20Gi
---
kind: Safekeeper
apiVersion: neon.oltp.molnett.org/v1alpha1
metadata:
  name: my-cluster-safekeeper-2
  namespace: neon
spec:
  id: 2
  cluster: my-cluster
  storageConfig:
    size: 5Gi
---
kind: Safekeeper
apiVersion: neon.oltp.molnett.org/v1alpha1
metadata:
  name: my-cluster-safekeeper-3
  namespace: neon
spec:
  id: 3
  cluster: my-cluster
  storageConfig:
    size: 5Gi
